name: treebiomass
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - torchvision
  - deepforest
  - detectree
  - segment-geospatial
  - groundingdino-py
  - segment-anything-fast
  - pip:
      - albumentations
      - python-dotenv
